const genres = [
  // Store Categories
  "Electronics & Gadgets",
  "Furniture & Home Decor",
  "General Store",
  "Clothing & Apparel",
  "Grocery & Supermarket",
  "Beauty & Personal Care",
  "Sports & Outdoors",
  "Books & Stationery",
  "Toys & Games",
  "Health & Wellness",
  "Automotive Parts",
  "Jewelry & Accessories",
  "Pet Supplies",
  "Office Supplies",
  "Home Improvement",
  "Baby & Kids",
  "Electronics Accessories",
  "Mobile Phones & Accessories",
  "Computers & Laptops",
  "Audio & Headphones",
  "Cameras & Photography",
  "TV & Home Theater",
  "Wearable Technology",
  "Gaming Consoles",
  "Smart Home Devices",
  "Kitchen Appliances",
  "Home Furniture",
  "Lighting & Ceiling Fans",
  "Home Storage",
  "Bedding & Bath",
  "Home Decor",
  "Garden & Outdoor",
  "Tools & Home Improvement",
  "Hardware",
  "Bathroom Fixtures",
  "Building Materials",
  "Electrical",
  "Plumbing",
  "Paint & Wall Treatments",
  "Flooring & Area Rugs",
  "Window Treatments",
  "Home Security",
  "Seasonal Decor",
  "Party Supplies",
  "Arts & Crafts",
  "Sewing & Fabric",
  "Musical Instruments",
  "Collectibles & Fine Art",
  "Industrial & Scientific",
  "Wholesale & Bulk",
  "Convenience Stores",
  "Specialty Food Stores",
  "Liquor & Beverage Stores",
  "Tobacco & Vape Shops",
  "Department Stores",
  "Discount Stores",
  "Thrift & Consignment Stores",
  "Luxury Goods",
  "Antiques & Collectibles",
  "Flea Markets",
  "Farmers Markets",
  "Convenience Stores & Gas Stations",
  "Duty-Free Shops",
  "Military Surplus",
  "Religious & Church Supplies",
  "Trophy & Awards",
  "Safety & Security Equipment"
];

export default genres;
